name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: ng build --configuration production --base-href /psn-store/

    - name: Configure Git
      run: |
        git config --global user.email "leosatcode@egmail.com"
        git config --global user.name "LeoSatCode"
        git remote set-url origin https://LeoSatCode:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/LeoSatCode/psn-store.git

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./dist/psn-store
